const answer = (text, points, ...accepted) => ({ text, points, accepted: [text, ...accepted] })

export const extraSurveyShowdownPrompts = [
  { id: 'ss-61', prompt: 'Name something people do before taking a photo.', answers: [answer('Smile', 31), answer('Fix their hair', 21, 'hair'), answer('Pose', 18), answer('Check the background', 12, 'background'), answer('Move closer together', 10, 'stand together'), answer('Say cheese', 8, 'cheese')] },
  { id: 'ss-62', prompt: 'Name something people buy at a petrol station besides fuel.', answers: [answer('Snacks', 29, 'crisps', 'sweets'), answer('Coffee', 23), answer('Water or soft drink', 18, 'drink'), answer('Milk', 11), answer('Newspaper', 10, 'paper'), answer('Car wash', 9)] },
  { id: 'ss-63', prompt: 'Name something that makes a room feel cosy.', answers: [answer('Warm lighting', 27, 'lamps', 'lighting'), answer('Blankets', 22, 'throws'), answer('Fireplace', 18, 'fire'), answer('Candles', 13), answer('Cushions', 11, 'pillows'), answer('A rug', 9, 'rug')] },
  { id: 'ss-64', prompt: 'Name something people do while stuck in traffic.', answers: [answer('Listen to music', 28, 'music', 'radio'), answer('Complain', 21), answer('Check the time', 17, 'time'), answer('Call someone', 13, 'phone call'), answer('Sing', 11), answer('Look for another route', 10, 'maps')] },
  { id: 'ss-65', prompt: 'Name something people might bring to a house party.', answers: [answer('Drinks', 31, 'drink'), answer('Snacks', 22, 'food'), answer('Dessert', 15, 'cake'), answer('A gift for the host', 12, 'gift'), answer('Games', 11, 'board game'), answer('Speaker', 9, 'music speaker')] },
  { id: 'ss-66', prompt: 'Name something children often ask for in a shop.', answers: [answer('Sweets', 30, 'candy'), answer('Toy', 24, 'toys'), answer('Chocolate', 17), answer('Ice cream', 12), answer('Magazine', 9), answer('Drink', 8)] },
  { id: 'ss-67', prompt: 'Name something people do to save money.', answers: [answer('Cook at home', 27, 'meal prep'), answer('Use discounts', 22, 'coupons'), answer('Cancel subscriptions', 17), answer('Buy second-hand', 13, 'used'), answer('Walk instead of driving', 11, 'walk'), answer('Make a budget', 10, 'budget')] },
  { id: 'ss-68', prompt: 'Name something that happens at a school sports day.', answers: [answer('Running races', 32, 'race'), answer('Parents cheering', 19, 'cheering'), answer('Egg-and-spoon race', 16), answer('Medals or certificates', 12, 'medals'), answer('Someone falls over', 11, 'fall'), answer('Picnic', 10)] },
  { id: 'ss-69', prompt: 'Name something people do when they cannot sleep.', answers: [answer('Check their phone', 28, 'phone'), answer('Read', 22, 'book'), answer('Watch TV', 17, 'tv'), answer('Get a drink', 12, 'water'), answer('Count sheep', 11), answer('Worry', 10, 'think')] },
  { id: 'ss-70', prompt: 'Name something people decorate for a celebration.', answers: [answer('Room or house', 29, 'house', 'room'), answer('Cake', 21), answer('Table', 17), answer('Garden', 12), answer('Car', 11), answer('Gift bag', 10, 'present')] },
  { id: 'ss-71', prompt: 'Name something people might do on their lunch break.', answers: [answer('Eat', 35, 'lunch'), answer('Go for a walk', 20, 'walk'), answer('Check phone', 15, 'phone'), answer('Run errands', 12, 'errands'), answer('Chat with colleagues', 10, 'talk'), answer('Work through it', 8, 'keep working')] },
  { id: 'ss-72', prompt: 'Name something people do when they hear their favourite song.', answers: [answer('Sing along', 31, 'sing'), answer('Dance', 24), answer('Turn it up', 16, 'increase volume'), answer('Smile', 11), answer('Tell someone', 10, 'share it'), answer('Add it to a playlist', 8, 'playlist')] },
]
