const answer = (text, points, ...accepted) => ({ text, points, accepted: [text, ...accepted] })

export const familyNightSurveyShowdownPrompts = [
  { id: 'ss-fn-01', prompt: 'Name something people do when the doorbell rings unexpectedly.', answers: [answer('Look through a window', 28, 'look outside'), answer('Check who it is', 24, 'ask who it is'), answer('Hide or stay quiet', 16, 'hide'), answer('Open the door', 14), answer('Turn down the TV', 10, 'pause tv'), answer('Call someone else', 8, 'shout for someone')] },
  { id: 'ss-fn-02', prompt: 'Name something found on a kitchen counter.', answers: [answer('Kettle', 28), answer('Toaster', 23), answer('Bread', 16), answer('Fruit bowl', 13, 'fruit'), answer('Coffee machine', 11, 'coffee maker'), answer('Keys', 9)] },
  { id: 'ss-fn-03', prompt: 'Name something people do during adverts on TV.', answers: [answer('Check their phone', 32, 'phone'), answer('Get a snack', 22, 'snacks'), answer('Make tea', 16, 'tea', 'coffee'), answer('Use the bathroom', 13, 'toilet'), answer('Talk', 10, 'chat'), answer('Fast-forward', 7, 'skip adverts')] },
  { id: 'ss-fn-04', prompt: 'Name a reason someone might not answer their phone.', answers: [answer('They are busy', 28, 'busy'), answer('Phone is on silent', 23, 'silent'), answer('They are driving', 17, 'driving'), answer('They do not recognise the number', 13, 'unknown number'), answer('Battery is dead', 11, 'dead battery'), answer('They are asleep', 8, 'sleeping')] },
  { id: 'ss-fn-05', prompt: 'Name something people keep in the car.', answers: [answer('Sunglasses', 23), answer('Phone charger', 21, 'charger'), answer('Umbrella', 17), answer('Shopping bags', 15, 'bags'), answer('Water bottle', 13, 'water'), answer('Spare change', 11, 'coins')] },
  { id: 'ss-fn-06', prompt: 'Name something people do before answering the front door.', answers: [answer('Check who it is', 28, 'look who it is'), answer('Tidy themselves up', 21, 'fix hair'), answer('Turn down the TV', 17, 'pause tv'), answer('Call for someone else', 13, 'shout for someone'), answer('Put on shoes', 11, 'shoes'), answer('Hide clutter', 10, 'tidy')] },
  { id: 'ss-fn-07', prompt: 'Name something that makes people sigh.', answers: [answer('Traffic', 24), answer('A long queue', 22, 'queue'), answer('Bad news', 18), answer('A bill', 14, 'bills'), answer('Rain', 12), answer('Slow internet', 10, 'wifi')] },
  { id: 'ss-fn-08', prompt: 'Name a food people often burn.', answers: [answer('Toast', 32), answer('Pizza', 20), answer('Sausages', 17), answer('Bacon', 12), answer('Popcorn', 10), answer('Rice', 9)] },
  { id: 'ss-fn-09', prompt: 'Name something children ask for at bedtime.', answers: [answer('A story', 27, 'book'), answer('A drink', 24, 'water'), answer('One more minute', 18, 'more time'), answer('A cuddle', 13, 'hug'), answer('The toilet', 10, 'bathroom'), answer('A night light', 8, 'light')] },
  { id: 'ss-fn-10', prompt: 'Name something people argue about on a shared TV.', answers: [answer('What to watch', 35, 'programme', 'show'), answer('Volume', 22), answer('Remote control', 15, 'remote'), answer('Skipping adverts', 11, 'adverts'), answer('Subtitles', 9), answer('Spoilers', 8)] },
  { id: 'ss-fn-11', prompt: 'Name something people do when a package arrives.', answers: [answer('Open it immediately', 30, 'open it'), answer('Check the label', 20, 'read label'), answer('Take it inside', 17, 'bring it in'), answer('Look for scissors', 13, 'get scissors'), answer('Tell someone', 11, 'message someone'), answer('Recycle the box', 9, 'throw box away')] },
  { id: 'ss-fn-12', prompt: 'Name something that runs out at the worst time.', answers: [answer('Phone battery', 29, 'battery'), answer('Toilet roll', 22, 'toilet paper'), answer('Milk', 17), answer('Petrol', 13, 'fuel'), answer('Hot water', 10), answer('Internet data', 9, 'data')] },
  { id: 'ss-fn-13', prompt: 'Name something people put in a lunchbox.', answers: [answer('Sandwich', 31), answer('Fruit', 22), answer('Crisps', 16, 'chips'), answer('Chocolate bar', 12, 'chocolate'), answer('Yoghurt', 10, 'yogurt'), answer('Juice box', 9, 'drink')] },
  { id: 'ss-fn-14', prompt: 'Name something people do when they enter a hotel room.', answers: [answer('Look at the bed', 25, 'check bed'), answer('Open the curtains', 20, 'curtains'), answer('Check the bathroom', 18, 'bathroom'), answer('Turn on the TV', 14, 'tv'), answer('Connect to Wi-Fi', 13, 'wifi'), answer('Unpack', 10)] },
  { id: 'ss-fn-15', prompt: 'Name something that can make a kitchen messy.', answers: [answer('Cooking', 30), answer('Baking', 21), answer('Children', 16, 'kids'), answer('Dirty dishes', 14, 'dishes'), answer('Spilled drinks', 11, 'spill'), answer('Pets', 8)] },
  { id: 'ss-fn-16', prompt: 'Name a thing people say when they are surprised.', answers: [answer('Oh my God', 26, 'omg'), answer('No way', 23), answer('Really?', 18, 'really'), answer('What?', 14), answer('You are joking', 11, 'joking'), answer('Wow', 8)] },
  { id: 'ss-fn-17', prompt: 'Name something people buy at a petrol station besides petrol.', answers: [answer('Coffee', 24), answer('Chocolate', 22), answer('Crisps', 18, 'chips'), answer('Water', 14), answer('Sandwich', 12), answer('Car wash', 10, 'wash')] },
  { id: 'ss-fn-18', prompt: 'Name something people do to make a room smell nicer.', answers: [answer('Light a candle', 27, 'candle'), answer('Open a window', 23, 'window'), answer('Use air freshener', 20, 'spray'), answer('Clean', 13), answer('Bake something', 9, 'bake'), answer('Use a diffuser', 8, 'diffuser')] },
  { id: 'ss-fn-19', prompt: 'Name something people check in the morning before leaving home.', answers: [answer('Weather', 28), answer('Phone', 21), answer('Keys', 18), answer('Traffic', 13), answer('Wallet or purse', 11, 'wallet', 'purse'), answer('Hair or outfit', 9, 'hair', 'clothes')] },
  { id: 'ss-fn-20', prompt: 'Name something that causes friendly arguments at game night.', answers: [answer('Rules', 29), answer('Scoring', 22, 'score'), answer('Cheating accusations', 17, 'cheating'), answer('Teams', 13), answer('A timer', 10, 'time'), answer('Who goes first', 9, 'turn order')] },
]
