export const familyNightQuickfire30Cards = [
  { id: 'qf30-fn-001', terms: ['A rolling pin', 'Croke Park', 'Taylor Swift', 'A traffic cone', 'The Toy Show'] },
  { id: 'qf30-fn-002', terms: ['A spice bag', 'Paddington Bear', 'The Cliffs of Moher', 'A penalty shootout', 'Netflix'] },
  { id: 'qf30-fn-003', terms: ['Barry’s Tea', 'The Eiffel Tower', 'Roy Keane', 'A birthday cake', 'Derry Girls'] },
  { id: 'qf30-fn-004', terms: ['A supermarket trolley', 'Harry Potter', 'The River Liffey', 'A red card', 'Beyonce'] },
  { id: 'qf30-fn-005', terms: ['A chicken fillet roll', 'The Simpsons', 'Katie Taylor', 'A leap card', 'Mount Everest'] },
  { id: 'qf30-fn-006', terms: ['A school jumper', 'Star Wars', 'Guinness', 'A free kick', 'The Louvre'] },
  { id: 'qf30-fn-007', terms: ['A hot press', 'Lionel Messi', 'The Late Late Show', 'A flat tyre', 'Buckingham Palace'] },
  { id: 'qf30-fn-008', terms: ['Tayto', 'Spider-Man', 'Galway', 'A yellow card', 'A karaoke machine'] },
  { id: 'qf30-fn-009', terms: ['A Sunday roast', 'The Traitors', 'Paul Mescal', 'A shopping receipt', 'The Grand Canyon'] },
  { id: 'qf30-fn-010', terms: ['The immersion', 'The Lion King', 'Cork', 'A bicycle kick', 'Google Maps'] },
  { id: 'qf30-fn-011', terms: ['Brown sauce', 'Friends', 'Cillian Murphy', 'A wedding speech', 'The Great Wall of China'] },
  { id: 'qf30-fn-012', terms: ['A county jersey', 'Toy Story', 'Dublin Zoo', 'A corner flag', 'A vending machine'] },
  { id: 'qf30-fn-013', terms: ['SuperValu', 'James Bond', 'Katie McCabe', 'A hotel key card', 'The Moon'] },
  { id: 'qf30-fn-014', terms: ['A 99 ice cream', 'Shrek', 'The Aran Islands', 'A drop goal', 'Instagram'] },
  { id: 'qf30-fn-015', terms: ['MiWadi', 'Home Alone', 'Johnny Sexton', 'A picnic blanket', 'The Statue of Liberty'] },
  { id: 'qf30-fn-016', terms: ['A toasted special', 'Frozen', 'Newgrange', 'A lineout', 'Spotify'] },
  { id: 'qf30-fn-017', terms: ['Dunnes Stores', 'The Matrix', 'Saoirse Ronan', 'A broken umbrella', 'Tokyo'] },
  { id: 'qf30-fn-018', terms: ['A packet of biscuits', 'Jurassic Park', 'The Ring of Kerry', 'A hat-trick', 'IKEA'] },
  { id: 'qf30-fn-019', terms: ['Kerrygold', 'The Office', 'Rory McIlroy', 'A train ticket', 'Las Vegas'] },
  { id: 'qf30-fn-020', terms: ['A deli counter', 'The Wizard of Oz', 'Temple Bar', 'A photo finish', 'TikTok'] },
  { id: 'qf30-fn-021', terms: ['Soda bread', 'The Avengers', 'Brian O’Driscoll', 'A phone charger', 'Paris'] },
  { id: 'qf30-fn-022', terms: ['A turf fire', 'Finding Nemo', 'Kilkenny', 'A scrum', 'YouTube'] },
  { id: 'qf30-fn-023', terms: ['Penney’s', 'Doctor Who', 'Enya', 'A shopping bag', 'Sydney Opera House'] },
  { id: 'qf30-fn-024', terms: ['Club Orange', 'Titanic', 'Phoenix Park', 'A sideline cut', 'Amazon'] },
  { id: 'qf30-fn-025', terms: ['A breakfast roll', 'Wicked', 'Niall Horan', 'A doorbell', 'Rome'] },
  { id: 'qf30-fn-026', terms: ['Ballygowan', 'Black Mirror', 'The Burren', 'A penalty save', 'Nintendo'] },
  { id: 'qf30-fn-027', terms: ['A wooden spoon', 'Matilda', 'Colin Farrell', 'A cinema ticket', 'London'] },
  { id: 'qf30-fn-028', terms: ['Centra', 'Stranger Things', 'Dingle', 'A yellow sliotar', 'Starbucks'] },
  { id: 'qf30-fn-029', terms: ['A jambon', 'Rocky', 'Joanne McNally', 'A birthday card', 'The Taj Mahal'] },
  { id: 'qf30-fn-030', terms: ['Lyons Tea', 'The Great British Bake Off', 'Glendalough', 'A rugby tackle', 'WhatsApp'] },
]
