export const launchGameTypes = [
  'one-percent',
  'majority-rules',
  'bluff-battle',
  'million-ladder',
  'survey-showdown',
  'quickfire-30',
  'say-what-you-see',
]

export const pricingTiers = [
  {
    key: 'free_demo',
    name: 'Free Demo',
    billingType: 'free',
    status: 'active',
    requiresUser: false,
    requiresEntitlement: false,
    priceCents: 0,
    currency: 'EUR',
    gameGrants: ['majority-rules', 'million-ladder'],
    featureGrants: [
      { featureKey: 'host_games' },
      { featureKey: 'room_size_cap', limit: 4 },
      { featureKey: 'built_in_question_pools' },
    ],
    metadata: {
      publicLabel: 'Free demo',
      publicAccess: true,
      guestsFree: true,
      signUpRequired: false,
      checkoutRequired: false,
    },
  },
  {
    key: 'family_pack_v1',
    name: 'Family Pack',
    billingType: 'one_time',
    status: 'active',
    requiresUser: true,
    requiresEntitlement: true,
    priceCents: 1999,
    currency: 'EUR',
    gameGrants: launchGameTypes,
    featureGrants: [
      { featureKey: 'host_games' },
      { featureKey: 'built_in_question_pools' },
    ],
    metadata: {
      publicLabel: 'Family Pack',
      version: 1,
      publicAccess: false,
      guestsFree: true,
      signUpRequired: true,
      includesFutureGames: false,
      includesCustomQuestions: false,
    },
  },
  {
    key: 'custom_edition_v1',
    name: 'Family Pack Plus / Custom Edition',
    billingType: 'one_time',
    status: 'active',
    requiresUser: true,
    requiresEntitlement: true,
    priceCents: 3999,
    currency: 'EUR',
    gameGrants: launchGameTypes,
    featureGrants: [
      { featureKey: 'host_games' },
      { featureKey: 'built_in_question_pools' },
      { featureKey: 'custom_questions' },
      { featureKey: 'custom_question_import' },
      { featureKey: 'reusable_custom_packs' },
    ],
    metadata: {
      publicLabel: 'Custom Edition',
      version: 1,
      publicAccess: false,
      guestsFree: true,
      signUpRequired: true,
      includesFutureGames: false,
      includesCustomQuestions: true,
    },
  },
  {
    key: 'club_pass_monthly',
    name: 'Club Pass',
    billingType: 'subscription',
    status: 'active',
    requiresUser: true,
    requiresEntitlement: true,
    priceCents: 999,
    currency: 'EUR',
    gameGrants: launchGameTypes,
    featureGrants: [
      { featureKey: 'host_games' },
      { featureKey: 'built_in_question_pools' },
      { featureKey: 'custom_questions' },
      { featureKey: 'custom_question_import' },
      { featureKey: 'reusable_custom_packs' },
      { featureKey: 'new_games' },
      { featureKey: 'official_question_packs' },
      { featureKey: 'seasonal_question_packs' },
      { featureKey: 'topical_question_packs' },
      { featureKey: 'early_access' },
    ],
    metadata: {
      publicLabel: 'Club Pass',
      billingInterval: 'month',
      publicAccess: false,
      guestsFree: true,
      signUpRequired: true,
      includesFutureGames: true,
      includesCustomQuestions: true,
    },
  },
]
