export const extraBluffPrompts = [
  { id: 'bb-extra-lego-name', prompt: 'The name LEGO comes from Danish words meaning what?', answer: 'Play well', explanation: 'LEGO comes from “leg godt”, meaning play well.' },
  { id: 'bb-extra-rubber-ducks', prompt: 'A 1992 shipping spill helped scientists track ocean currents using thousands of what bath toys?', answer: 'Rubber ducks', explanation: 'Floating bath toys from a lost container were tracked across oceans.' },
  { id: 'bb-extra-paper-fold', prompt: 'What is the common name for the Japanese art of paper folding?', answer: 'Origami', explanation: 'Origami is the traditional art of folding paper into shapes.' },
  { id: 'bb-extra-mona-lisa', prompt: 'In which museum is the Mona Lisa displayed?', answer: 'The Louvre', explanation: 'Leonardo da Vinci’s Mona Lisa is displayed in the Louvre in Paris.' },
  { id: 'bb-extra-honey-spoil', prompt: 'Which sweet food is famous for lasting for extremely long periods without spoiling?', answer: 'Honey', explanation: 'Low moisture and acidity help sealed honey remain edible for a very long time.' },
  { id: 'bb-extra-typewriter-row', prompt: 'Which word can be typed using only the top row of a QWERTY keyboard?', answer: 'Typewriter', explanation: 'TYPEWRITER uses only letters from the top keyboard row.' },
  { id: 'bb-extra-statue-copper', prompt: 'The Statue of Liberty is green because its outside is made of which metal?', answer: 'Copper', explanation: 'Weathered copper forms a green patina over time.' },
  { id: 'bb-extra-blue-whale-heart', prompt: 'The heart of a blue whale is roughly the size of what small vehicle?', answer: 'A small car', explanation: 'A blue whale heart can weigh hundreds of kilograms and is often compared to a small car.' },
  { id: 'bb-extra-olympic-rings', prompt: 'How many rings are on the Olympic flag?', answer: '5', inputMode: 'numeric', explanation: 'The Olympic symbol has five interlocking rings.' },
  { id: 'bb-extra-fortnight', prompt: 'How many days are in a fortnight?', answer: '14', inputMode: 'numeric', explanation: 'A fortnight is two weeks.' },
  { id: 'bb-extra-vinyl-speed', prompt: 'What does RPM stand for on a record player?', answer: 'Revolutions per minute', explanation: 'RPM measures how many full turns happen each minute.' },
  { id: 'bb-extra-piano-keys', prompt: 'How many keys are on a standard modern piano?', answer: '88', inputMode: 'numeric', explanation: 'Most full-size modern pianos have 88 keys.' },
  { id: 'bb-extra-venus-spin', prompt: 'Which planet spins in the opposite direction to most planets in the Solar System?', answer: 'Venus', explanation: 'Venus has retrograde rotation compared with most planets.' },
  { id: 'bb-extra-bread-toaster', prompt: 'What does a toaster mainly use to brown bread?', answer: 'Radiant heat', explanation: 'Glowing heating elements radiate heat onto the bread.' },
  { id: 'bb-extra-braille-cells', prompt: 'How many dot positions are in a standard Braille cell?', answer: '6', inputMode: 'numeric', explanation: 'A standard Braille cell has six possible dot positions.' },
  { id: 'bb-extra-tin-can', prompt: 'What metal is usually only a thin coating on a traditional tin can?', answer: 'Tin', explanation: 'Many tin cans are steel with a thin protective tin coating.' },
  { id: 'bb-extra-pencils-graphite', prompt: 'The “lead” in a pencil is actually mostly what material?', answer: 'Graphite', explanation: 'Pencil cores are graphite mixed with clay, not metallic lead.' },
  { id: 'bb-extra-compass-red', prompt: 'On many compasses, the red end of the needle points roughly towards which direction?', answer: 'North', explanation: 'The marked needle end is used to indicate magnetic north.' },
  { id: 'bb-extra-sos', prompt: 'The distress signal SOS was chosen mainly because it is what?', answer: 'Easy to send in Morse code', explanation: 'Three dots, three dashes, three dots is simple and recognisable.' },
  { id: 'bb-extra-iceberg', prompt: 'Roughly what fraction of an iceberg is below the waterline?', answer: 'Nine tenths', explanation: 'About 90 percent of an iceberg’s volume is underwater.' },
]
