export const familyNightBluffPrompts = [
  { id: 'bb-fn-penguin-knees', prompt: 'Which bird looks like it has very short legs because much of its leg is hidden inside its body?', answer: 'A penguin', explanation: 'Penguins have longer leg bones than they appear to have from the outside.' },
  { id: 'bb-fn-croissant-origin', prompt: 'The croissant is strongly associated with France, but its ancestor is usually linked to which country?', answer: 'Austria', explanation: 'The kipferl, an Austrian crescent-shaped pastry, is a common ancestor of the croissant.' },
  { id: 'bb-fn-moon-footprints', prompt: 'Why can astronauts’ footprints remain on the Moon for an extremely long time?', answer: 'There is no wind or rain', explanation: 'Without weather like wind and rain, footprints are not quickly erased.' },
  { id: 'bb-fn-pencil-lines', prompt: 'What household item is often measured with the HB grading scale?', answer: 'A pencil', explanation: 'HB describes the hardness and blackness of pencil graphite.' },
  { id: 'bb-fn-kiwi-bird', prompt: 'Which flightless bird shares its name with a fruit?', answer: 'Kiwi', explanation: 'The kiwi is a bird from New Zealand as well as the name of the fruit.' },
  { id: 'bb-fn-traffic-lights', prompt: 'Which colour is normally at the top of a vertical traffic light?', answer: 'Red', explanation: 'Standard vertical traffic lights place red at the top.' },
  { id: 'bb-fn-goldfish-memory', prompt: 'Contrary to the old myth, goldfish can remember things for longer than roughly how many seconds?', answer: '3', inputMode: 'numeric', explanation: 'The “three-second memory” claim is a myth; goldfish can learn and remember for much longer.' },
  { id: 'bb-fn-human-taste', prompt: 'Which taste is associated with savoury foods and is often called the fifth basic taste?', answer: 'Umami', explanation: 'Umami is the savoury taste linked with glutamates.' },
  { id: 'bb-fn-dream-rem', prompt: 'The sleep stage most associated with vivid dreaming is abbreviated as what?', answer: 'REM', explanation: 'REM stands for rapid eye movement sleep.' },
  { id: 'bb-fn-pineapple-berries', prompt: 'A pineapple is made from many flowers joined together, making it what kind of fruit?', answer: 'A multiple fruit', explanation: 'Pineapples form from a cluster of flowers that fuse into one fruit.' },
  { id: 'bb-fn-venus-day-year', prompt: 'On Venus, which is longer: one day or one year?', answer: 'One day', explanation: 'Venus rotates so slowly that a Venusian day is longer than its year.' },
  { id: 'bb-fn-ice-floating', prompt: 'Why does ice float in water?', answer: 'It is less dense than liquid water', explanation: 'Water expands as it freezes, making ice less dense.' },
  { id: 'bb-fn-bread-holes', prompt: 'What gas mostly makes bread dough rise?', answer: 'Carbon dioxide', explanation: 'Yeast produces carbon dioxide bubbles during fermentation.' },
  { id: 'bb-fn-library-dewey', prompt: 'What decimal classification system is commonly used to organise library books?', answer: 'Dewey Decimal', explanation: 'The Dewey Decimal system groups books by subject using numbers.' },
  { id: 'bb-fn-battery-terminals', prompt: 'What symbol marks the positive terminal on a battery?', answer: 'Plus', explanation: 'The positive end is usually marked with a plus sign.' },
  { id: 'bb-fn-honeybees-dance', prompt: 'What kind of movement do honeybees use to show other bees where food is?', answer: 'A waggle dance', explanation: 'The waggle dance communicates direction and distance to food.' },
  { id: 'bb-fn-map-lines', prompt: 'Lines of longitude meet at which two places?', answer: 'The poles', explanation: 'All meridians of longitude converge at the North and South Poles.' },
  { id: 'bb-fn-hot-air-balloon', prompt: 'What makes a hot-air balloon rise?', answer: 'Hot air is less dense', explanation: 'Heating the air inside the balloon makes it less dense than the surrounding air.' },
  { id: 'bb-fn-silver-symbol', prompt: 'What is the chemical symbol for silver?', answer: 'Ag', explanation: 'Ag comes from silver’s Latin name, argentum.' },
  { id: 'bb-fn-monopoly-jail', prompt: 'In Monopoly, what square can you be sent to by a card, dice roll, or board instruction?', answer: 'Jail', explanation: 'Several routes in Monopoly can send a player to Jail.' },
  { id: 'bb-fn-rainbow-order', prompt: 'What colour comes after green in the usual rainbow order?', answer: 'Blue', explanation: 'The common sequence is red, orange, yellow, green, blue, indigo, violet.' },
  { id: 'bb-fn-morse-s', prompt: 'In Morse code, the letter S is made of how many dots?', answer: '3', inputMode: 'numeric', explanation: 'S is dot-dot-dot in Morse code.' },
  { id: 'bb-fn-elevator-name', prompt: 'What is a lift called in American English?', answer: 'An elevator', explanation: 'In the US, a lift is commonly called an elevator.' },
  { id: 'bb-fn-tug-of-war', prompt: 'What sport was once an official Olympic event and involves teams pulling a rope?', answer: 'Tug of war', explanation: 'Tug of war was contested at several early modern Olympic Games.' },
  { id: 'bb-fn-candle-wax', prompt: 'A candle flame mainly melts and burns which material?', answer: 'Wax', explanation: 'The flame melts wax, which travels up the wick and burns as vapour.' },
]
