import { selectPrompts } from '../selectPrompts.js'
import { extraBluffPrompts } from './extraPrompts.js'

export const bluffPromptPool = [
  {
    id: 'wombat-cubes',
    prompt: 'Wombats are famous for producing droppings shaped like what?',
    answer: 'Cubes',
    explanation: 'Different elasticity in the wombat intestine forms the droppings into cubes.',
  },
  {
    id: 'banana-berry',
    prompt: 'Botanically speaking, a banana is classified as what?',
    answer: 'A berry',
    explanation: 'Bananas develop from a single flower with one ovary, making them botanical berries.',
  },
  {
    id: 'scotland-animal',
    prompt: 'What is the national animal of Scotland?',
    answer: 'The unicorn',
    explanation: 'The unicorn has been a Scottish heraldic symbol for centuries.',
  },
  {
    id: 'octopus-hearts',
    prompt: 'How many hearts does an octopus have?',
    answer: '3',
    inputMode: 'numeric',
    explanation: 'Two pump blood through the gills and one pumps it around the body.',
  },
  {
    id: 'flamingo-group',
    prompt: 'What wonderfully dramatic name is given to a group of flamingos?',
    answer: 'A flamboyance',
    explanation: 'A group of flamingos is commonly called a flamboyance.',
  },
  {
    id: 'sea-otter-sleep',
    prompt: 'What do sea otters sometimes do while sleeping so they do not drift apart?',
    answer: 'Hold hands',
    explanation: 'Sea otters may hold paws while resting together in floating groups called rafts.',
  },
  {
    id: 'inventor-pringle',
    prompt: 'Part of the ashes of the inventor of the Pringles can were buried in what?',
    answer: 'A Pringles can',
    explanation: 'Fredric Baur requested that some of his ashes be placed inside his famous invention.',
  },
  {
    id: 'cow-friends',
    prompt: 'Research suggests cows become less stressed when they are near what?',
    answer: 'Their best friend',
    explanation: 'Studies have observed lower stress indicators when preferred cow partners are together.',
  },
  {
    id: 'raven-group',
    prompt: 'What is one traditional collective noun for a group of ravens?',
    answer: 'An unkindness',
    explanation: 'An unkindness is one of the traditional names used for a group of ravens.',
  },
  {
    id: 'space-smell',
    prompt: 'Astronauts have compared the smell clinging to spacesuits after a spacewalk to what?',
    answer: 'Seared steak',
    explanation: 'Descriptions include seared steak, hot metal, and welding fumes.',
  },
  {
    id: 'goat-eyes',
    prompt: 'What unusual shape are the pupils in a goat’s eyes?',
    answer: 'Rectangular',
    explanation: 'Horizontal rectangular pupils give grazing animals a wide field of view.',
  },
  {
    id: 'butterfly-feet',
    prompt: 'Butterflies taste food using which part of their body?',
    answer: 'Their feet',
    explanation: 'Taste receptors on their feet help butterflies identify suitable plants.',
  },
  {
    id: 'shrimp-heart',
    prompt: 'A shrimp’s heart is located in which part of its body?',
    answer: 'Its head',
    explanation: 'The heart sits in the cephalothorax, the fused head-and-thorax region.',
  },
  {
    id: 'parrot-names',
    prompt: 'Wild parrots have been observed giving their chicks something resembling what?',
    answer: 'Names',
    explanation: 'Distinctive contact calls function rather like individual names within a flock.',
  },
  {
    id: 'hippo-sweat',
    prompt: 'What colour can the oily skin secretion of a hippopotamus appear?',
    answer: 'Red',
    explanation: 'Pigments in the secretion can make it look reddish and help protect the skin.',
  },
  {
    id: 'snail-sleep',
    prompt: 'In extreme conditions, some land snails can remain dormant for roughly how many years?',
    answer: '3',
    inputMode: 'numeric',
    explanation: 'Some species can enter extended dormancy to survive prolonged dry conditions.',
  },
  {
    id: 'penguin-pebble',
    prompt: 'A male gentoo penguin may present a female with what during courtship?',
    answer: 'A pebble',
    explanation: 'Pebbles are valuable nesting material and may be offered during courtship.',
  },
  {
    id: 'crow-faces',
    prompt: 'Crows can remember and recognise individual human what?',
    answer: 'Faces',
    explanation: 'Experiments show that crows can remember people they associate with danger.',
  },
  {
    id: 'koala-fingerprints',
    prompt: 'The fingerprints of which animal can look remarkably similar to human fingerprints?',
    answer: 'Koalas',
    explanation: 'Koalas have detailed fingertip ridges that can closely resemble ours.',
  },
  {
    id: 'herring-communication',
    prompt: 'Herring have been observed communicating at night by releasing what?',
    answer: 'Bubbles from their backsides',
    explanation: 'Researchers recorded distinctive sounds produced as herring release gas bubbles.',
  },
  {
    id: 'ostrich-eyes',
    prompt: 'Which part of an ostrich is larger than its brain?',
    answer: 'Its eye',
    explanation: 'Each ostrich eye is roughly the size of a billiard ball and is larger than its brain.',
  },
  {
    id: 'owl-group',
    prompt: 'What is the traditional collective noun for a group of owls?',
    answer: 'A parliament',
    explanation: 'A parliament is the best-known traditional collective noun for a group of owls.',
  },
  {
    id: 'hummingbird-reverse',
    prompt: 'Which bird is able to fly backwards?',
    answer: 'A hummingbird',
    explanation: 'Its unusual shoulder joints let it rotate its wings and generate lift in reverse.',
  },
  {
    id: 'polar-bear-skin',
    prompt: 'What colour is a polar bear’s skin beneath its fur?',
    answer: 'Black',
    explanation: 'Polar bears have black skin beneath translucent, light-scattering fur.',
  },
  {
    id: 'giraffe-tongue',
    prompt: 'What unusual colour is much of a giraffe’s tongue?',
    answer: 'Dark purple',
    explanation: 'The dark pigmentation may help protect the tongue during long hours of feeding in sunlight.',
  },
  {
    id: 'wood-frog-winter',
    prompt: 'What extraordinary thing can a wood frog do to survive winter?',
    answer: 'Freeze solid',
    explanation: 'Wood frogs can survive with much of their body water frozen before thawing in spring.',
  },
  {
    id: 'dolphin-sleep',
    prompt: 'How does a dolphin sleep without completely losing awareness?',
    answer: 'With half its brain at a time',
    explanation: 'Dolphins use unihemispheric sleep, resting one half of the brain while the other stays alert.',
  },
  {
    id: 'sea-cucumber-defence',
    prompt: 'What can some sea cucumbers eject from their body to distract predators?',
    answer: 'Their internal organs',
    explanation: 'Some species expel sticky tubes or internal organs and later regenerate them.',
  },
  {
    id: 'frog-drink',
    prompt: 'Rather than drinking through their mouths, frogs absorb much of their water through what?',
    answer: 'Their skin',
    explanation: 'A specialised patch of skin on the belly and thighs absorbs water directly.',
  },
  {
    id: 'butterfly-group',
    prompt: 'What dreamy collective noun can be used for a group of butterflies?',
    answer: 'A kaleidoscope',
    explanation: 'A kaleidoscope is a widely used collective noun for a group of butterflies.',
  },
  {
    id: 'snail-teeth',
    prompt: 'A garden snail can have roughly how many tiny teeth?',
    answer: '14,000',
    inputMode: 'numeric',
    explanation: 'Its ribbon-like radula is covered with thousands of microscopic teeth.',
  },
  {
    id: 'turtle-breathe',
    prompt: 'Some turtles can absorb oxygen underwater through which unexpected body part?',
    answer: 'Their backside',
    explanation: 'Certain turtles use cloacal respiration, exchanging gases through tissue near the rear opening.',
  },
  {
    id: 'venus-day',
    prompt: 'On which planet does one rotation take longer than one trip around the Sun?',
    answer: 'Venus',
    explanation: 'Venus rotates in about 243 Earth days but orbits the Sun in about 225.',
  },
  {
    id: 'sharks-trees',
    prompt: 'Which living animals existed on Earth before the first trees?',
    answer: 'Sharks',
    explanation: 'Shark ancestors appeared tens of millions of years before the earliest known trees.',
  },
  {
    id: 'antarctica-desert',
    prompt: 'What is the largest desert on Earth?',
    answer: 'Antarctica',
    explanation: 'Deserts are defined by low precipitation, making Antarctica the world’s largest.',
  },
  {
    id: 'lightning-temperature',
    prompt: 'Lightning can briefly become hotter than the surface of what?',
    answer: 'The Sun',
    explanation: 'A lightning channel can reach around 30,000°C, several times hotter than the Sun’s surface.',
  },
  {
    id: 'eiffel-summer',
    prompt: 'What can happen to the Eiffel Tower on a hot summer day?',
    answer: 'It gets taller',
    explanation: 'Thermal expansion can make the iron structure grow by several centimetres.',
  },
  {
    id: 'gallium-hand',
    prompt: 'What can happen if you hold a piece of the metal gallium in your hand?',
    answer: 'It melts',
    explanation: 'Gallium melts at about 29.8°C, low enough to liquefy in a warm hand.',
  },
  {
    id: 'space-sunset',
    prompt: 'What colour can sunsets appear on Mars?',
    answer: 'Blue',
    explanation: 'Fine Martian dust scatters light so the glow near the setting Sun can appear blue.',
  },
  {
    id: 'moon-footprints',
    prompt: 'Why may astronauts’ footprints remain on the Moon for millions of years?',
    answer: 'There is no wind or rain',
    explanation: 'With almost no atmosphere or liquid water, familiar weather cannot quickly erase them.',
  },
  {
    id: 'shortest-war',
    prompt: 'The shortest recorded war, fought between Britain and Zanzibar, lasted roughly how many minutes?',
    answer: '40',
    inputMode: 'numeric',
    explanation: 'The Anglo-Zanzibar War of 1896 ended in well under an hour.',
  },
  {
    id: 'oxford-aztec',
    prompt: 'Oxford University was already teaching students before the rise of which famous empire?',
    answer: 'The Aztec Empire',
    explanation: 'Teaching existed at Oxford by 1096; the Aztec Empire formed in the 15th century.',
  },
  {
    id: 'nintendo-founded',
    prompt: 'Nintendo was founded in 1889 to make what kind of product?',
    answer: 'Playing cards',
    explanation: 'The company began in Kyoto producing handmade hanafuda playing cards.',
  },
  {
    id: 'first-popsicle',
    prompt: 'How old was the inventor who accidentally created the first Popsicle-style ice pop?',
    answer: '11',
    inputMode: 'numeric',
    explanation: 'Frank Epperson was 11 when a flavoured drink and stirring stick froze outside overnight.',
  },
  {
    id: 'bubble-wrap-original',
    prompt: 'Bubble Wrap was originally invented to be used as what?',
    answer: 'Wallpaper',
    explanation: 'Its inventors first tried to market the sealed plastic texture as three-dimensional wallpaper.',
  },
  {
    id: 'playdoh-original',
    prompt: 'Before becoming a toy, Play-Doh was sold for what household job?',
    answer: 'Cleaning wallpaper',
    explanation: 'The soft compound was first used to lift soot from wallpaper.',
  },
  {
    id: 'microwave-discovery',
    prompt: 'What melted in Percy Spencer’s pocket and helped inspire the microwave oven?',
    answer: 'A chocolate bar',
    explanation: 'Microwave energy from radar equipment melted a candy bar in the engineer’s pocket.',
  },
  {
    id: 'velcro-inspiration',
    prompt: 'Velcro was inspired by what sticking to an inventor’s clothes and dog?',
    answer: 'Burrs',
    explanation: 'George de Mestral studied the tiny hooks on burrs after a walk in the Alps.',
  },
  {
    id: 'qr-purpose',
    prompt: 'QR codes were first developed to track what in Japanese factories?',
    answer: 'Car parts',
    explanation: 'Denso Wave created QR codes to track automotive components during manufacturing.',
  },
  {
    id: 'can-opener-delay',
    prompt: 'Which was invented first: the food can or the can opener?',
    answer: 'The food can',
    explanation: 'Canned food existed for decades before a dedicated can opener was patented.',
  },
  {
    id: 'dot-letter-name',
    prompt: 'What is the dot above a lowercase i or j called?',
    answer: 'A tittle',
    explanation: 'Tittle is the typographic name for that small distinguishing mark.',
  },
  {
    id: 'hashtag-name',
    prompt: 'What eight-letter name is sometimes used for the # symbol?',
    answer: 'Octothorpe',
    explanation: 'Octothorpe became a recognised name for the symbol in telecommunications.',
  },
  {
    id: 'alphabet-no-country',
    prompt: 'Which letter does not appear in the name of any US state?',
    answer: 'Q',
    explanation: 'Every letter except Q appears in at least one US state name.',
  },
  {
    id: 'dream-blind',
    prompt: 'People who have been blind from birth can experience dreams using what?',
    answer: 'Their other senses',
    explanation: 'Their dreams can include sound, touch, smell, taste, movement, and emotion.',
  },
  {
    id: 'nose-memory',
    prompt: 'Which sense is especially closely linked to memory and emotion?',
    answer: 'Smell',
    explanation: 'Smell pathways connect closely with brain regions involved in memory and emotion.',
  },
  {
    id: 'most-time-zones',
    prompt: 'Including overseas territories, which country spans the most time zones?',
    answer: 'France',
    explanation: 'France’s overseas territories give it more time zones than any other country.',
  },
  {
    id: 'vatican-size',
    prompt: 'What is the smallest independent country in the world?',
    answer: 'Vatican City',
    explanation: 'Vatican City covers less than half a square kilometre.',
  },
  {
    id: 'canada-coast',
    prompt: 'Which country has the longest coastline in the world?',
    answer: 'Canada',
    explanation: 'Canada’s mainland and many islands give it the world’s longest coastline.',
  },
  {
    id: 'russia-continents',
    prompt: 'Russia stretches across which two continents?',
    answer: 'Europe and Asia',
    explanation: 'The Ural Mountains conventionally divide Russia’s European and Asian regions.',
  },
  {
    id: 'earth-water',
    prompt: 'About what percentage of Earth’s surface is covered by water?',
    answer: '71',
    inputMode: 'numeric',
    explanation: 'Oceans and other water cover roughly 71% of Earth’s surface.',
  },
  ...extraBluffPrompts,
]

export function selectBluffPrompts(count = 5, excludedIds = new Set()) {
  return selectPrompts(bluffPromptPool, count, excludedIds)
}
