export const familyNightSayWhatYouSeePuzzles = [
  {
    id: 'swys-fn-high-noon',
    answer: 'High noon',
    acceptedOverride: ['High noon'],
    explanation: 'NOON is placed high on the board.',
    layout: 'high-five',
    tokens: ['NOON'],
  },
  {
    id: 'swys-fn-big-picture',
    answer: 'Big picture',
    acceptedOverride: ['Big picture', 'The big picture'],
    explanation: 'PICTURE is written very big.',
    layout: 'big-deal',
    tokens: ['PICTURE'],
  },
  {
    id: 'swys-fn-small-print',
    answer: 'Small print',
    acceptedOverride: ['Small print', 'The small print'],
    explanation: 'PRINT is written very small.',
    layout: 'small-talk',
    tokens: ['PRINT'],
  },
  {
    id: 'swys-fn-under-pressure',
    answer: 'Under pressure',
    acceptedOverride: ['Under pressure'],
    explanation: 'UNDER is underneath PRESSURE.',
    layout: 'under-cover',
    tokens: ['PRESSURE', 'UNDER'],
  },
  {
    id: 'swys-fn-top-table',
    answer: 'Top table',
    acceptedOverride: ['Top table', 'The top table'],
    explanation: 'TABLE is at the top.',
    layout: 'top-secret',
    tokens: ['TABLE'],
  },
  {
    id: 'swys-fn-down-payment',
    answer: 'Down payment',
    acceptedOverride: ['Down payment', 'A down payment'],
    explanation: 'DOWN points to PAYMENT.',
    layout: 'down-earth',
    tokens: ['DOWN', 'PAYMENT'],
  },
  {
    id: 'swys-fn-mixed-messages',
    answer: 'Mixed messages',
    acceptedOverride: ['Mixed messages', 'Mixed message'],
    explanation: 'The messages are mixed around the board.',
    layout: 'mixed-feelings',
    tokens: ['YES', 'NO', 'MAYBE', 'LATER'],
  },
  {
    id: 'swys-fn-time-flies',
    answer: 'Time flies',
    acceptedOverride: ['Time flies'],
    explanation: 'TIME is rising away like it is flying.',
    layout: 'rising-star',
    tokens: ['TIME'],
  },
  {
    id: 'swys-fn-life-in-the-fast-lane',
    answer: 'Life in the fast lane',
    acceptedOverride: ['Life in the fast lane', 'Fast lane'],
    explanation: 'LIFE is inside a lane.',
    layout: 'cycle-lane',
    tokens: ['LIFE'],
  },
  {
    id: 'swys-fn-back-to-back',
    answer: 'Back to back',
    acceptedOverride: ['Back to back'],
    explanation: 'Two BACKs are placed back to back.',
    layout: 'time-after-time',
    tokens: ['BACK', 'BACK'],
  },
  {
    id: 'swys-fn-head-start',
    answer: 'Big finish',
    acceptedOverride: ['Big finish', 'A big finish'],
    explanation: 'FINISH appears at the end and is the biggest word.',
    layout: 'last-largest',
    tokens: ['first', 'middle', 'FINISH'],
  },
  {
    id: 'swys-fn-cross-purposes',
    answer: 'Cross purposes',
    acceptedOverride: ['Cross purposes', 'At cross purposes'],
    explanation: 'Two PURPOSE words cross each other.',
    layout: 'crossroads',
    tokens: ['PURPOSE', 'PURPOSE'],
  },
  {
    id: 'swys-fn-round-the-clock',
    answer: 'Round the clock',
    acceptedOverride: ['Round the clock', 'Around the clock'],
    explanation: 'CLOCK is inside a round shape.',
    layout: 'blue-moon',
    tokens: ['CLOCK', 'ROUND'],
  },
  {
    id: 'swys-fn-safe-bet',
    answer: 'Safe bet',
    acceptedOverride: ['Safe bet', 'A safe bet'],
    explanation: 'BET is sitting safely inside the box.',
    layout: 'inside-job',
    tokens: ['BET'],
  },
  {
    id: 'swys-fn-right-between-eyes',
    answer: 'Eye to eye',
    acceptedOverride: ['Eye to eye', 'See eye to eye'],
    explanation: 'Two EYES are facing each other across the board.',
    layout: 'blank-space',
    tokens: ['EYE', 'EYE'],
  },
  {
    id: 'swys-fn-one-step-ahead',
    answer: 'One step at a time',
    acceptedOverride: ['One step at a time'],
    explanation: 'Each STEP climbs the board one at a time.',
    layout: 'step-by-step',
    tokens: ['STEP', 'STEP', 'STEP'],
  },
  {
    id: 'swys-fn-over-the-top',
    answer: 'Over the top',
    acceptedOverride: ['Over the top'],
    explanation: 'OVER is above TOP.',
    layout: 'head-heels',
    tokens: ['OVER', 'TOP'],
  },
  {
    id: 'swys-fn-no-end-in-sight',
    answer: 'No end in sight',
    acceptedOverride: ['No end in sight', 'No end'],
    explanation: 'END has a big NO across it.',
    layout: 'no-idea',
    tokens: ['END', 'NO'],
  },
  {
    id: 'swys-fn-eye-level',
    answer: 'Eye level',
    acceptedOverride: ['Eye level', 'At eye level'],
    explanation: 'EYE and LEVEL are sitting level with each other.',
    layout: 'stand-by-me',
    tokens: ['EYE', 'LEVEL'],
  },
  {
    id: 'swys-fn-short-story',
    answer: 'Short story',
    acceptedOverride: ['Short story', 'A short story'],
    explanation: 'STORY is shown as a very short word block.',
    layout: 'long-story-short',
    tokens: ['STORY', 'STORY'],
  },
]
