import { selectPrompts } from '../selectPrompts.js'

export const sayWhatYouSeePuzzles = [
  {
    id: 'swys-back-to-square-one',
    answer: 'Back to square one',
    acceptedOverride: ['Back to square one', 'Back square one'],
    explanation: 'The word BACK is literally returning to the first square.',
    layout: 'square-one',
    tokens: ['BACK', '1'],
  },
  {
    id: 'swys-read-between-lines',
    answer: 'Read between the lines',
    acceptedOverride: ['Read between the lines', 'Reading between the lines'],
    explanation: 'READ is sitting between two lines.',
    layout: 'between-lines',
    tokens: ['READ'],
  },
  {
    id: 'swys-over-the-moon',
    answer: 'Over the moon',
    acceptedOverride: ['Over the moon', 'Over moon'],
    explanation: 'The word OVER is placed above the moon.',
    layout: 'over-moon',
    tokens: ['OVER', 'MOON'],
  },
  {
    id: 'swys-long-time-no-see',
    answer: 'Long time no see',
    acceptedOverride: ['Long time no see'],
    explanation: 'TIME is stretched out and the word SEE is missing.',
    layout: 'long-time',
    tokens: ['T I M E'],
  },
  {
    id: 'swys-corner-shop',
    answer: 'Corner shop',
    acceptedOverride: ['Corner shop', 'The corner shop'],
    explanation: 'SHOP is tucked into the corner.',
    layout: 'corner-shop',
    tokens: ['SHOP'],
  },
  {
    id: 'swys-double-cross',
    answer: 'Double cross',
    acceptedOverride: ['Double cross', 'Two crosses'],
    explanation: 'There are two crosses.',
    layout: 'double-cross',
    tokens: ['X', 'X'],
  },
  {
    id: 'swys-rising-star',
    answer: 'Rising star',
    acceptedOverride: ['Rising star', 'A rising star'],
    explanation: 'The star is rising upward.',
    layout: 'rising-star',
    tokens: ['STAR'],
  },
  {
    id: 'swys-head-over-heels',
    answer: 'Head over heels',
    acceptedOverride: ['Head over heels', 'Head over heel'],
    explanation: 'HEAD is above HEELS.',
    layout: 'head-heels',
    tokens: ['HEAD', 'HEELS'],
  },
  {
    id: 'swys-step-by-step',
    answer: 'Step by step',
    acceptedOverride: ['Step by step', 'Step-by-step'],
    explanation: 'The word STEP climbs one step at a time.',
    layout: 'step-by-step',
    tokens: ['STEP', 'STEP', 'STEP'],
  },
  {
    id: 'swys-mixed-feelings',
    answer: 'Mixed feelings',
    acceptedOverride: ['Mixed feelings', 'Mixed feeling'],
    explanation: 'The feeling words are mixed together.',
    layout: 'mixed-feelings',
    tokens: ['JOY', 'FEAR', 'CALM', 'RAGE'],
  },
  {
    id: 'swys-cycle-lane',
    answer: 'Cycle lane',
    acceptedOverride: ['Cycle lane', 'Bike lane'],
    explanation: 'A cycle is inside a lane.',
    layout: 'cycle-lane',
    tokens: ['CYCLE'],
  },
  {
    id: 'swys-last-but-not-least',
    answer: 'Last but not least',
    acceptedOverride: ['Last but not least'],
    explanation: 'LAST appears at the end, but it is the largest word.',
    layout: 'last-largest',
    tokens: ['first', 'middle', 'LAST'],
  },
  {
    id: 'swys-middle-of-nowhere',
    answer: 'Middle of nowhere',
    acceptedOverride: ['Middle of nowhere', 'In the middle of nowhere'],
    explanation: 'MIDDLE is surrounded by NOWHERE.',
    layout: 'middle-nowhere',
    tokens: ['NO', 'MIDDLE', 'WHERE'],
  },
  {
    id: 'swys-time-after-time',
    answer: 'Time after time',
    acceptedOverride: ['Time after time'],
    explanation: 'One TIME comes after another TIME.',
    layout: 'time-after-time',
    tokens: ['TIME', 'TIME'],
  },
  {
    id: 'swys-down-to-earth',
    answer: 'Down to earth',
    acceptedOverride: ['Down to earth'],
    explanation: 'DOWN points directly to EARTH.',
    layout: 'down-earth',
    tokens: ['DOWN', 'EARTH'],
  },
  {
    id: 'swys-top-secret',
    answer: 'Top secret',
    acceptedOverride: ['Top secret'],
    explanation: 'SECRET is at the top of the board.',
    layout: 'top-secret',
    tokens: ['SECRET'],
  },
  {
    id: 'swys-under-cover',
    answer: 'Under cover',
    acceptedOverride: ['Under cover', 'Undercover'],
    explanation: 'UNDER is sitting under COVER.',
    layout: 'under-cover',
    tokens: ['COVER', 'UNDER'],
  },
  {
    id: 'swys-high-five',
    answer: 'High five',
    acceptedOverride: ['High five', 'A high five'],
    explanation: 'The number five is high on the board.',
    layout: 'high-five',
    tokens: ['5'],
  },
  {
    id: 'swys-big-deal',
    answer: 'Big deal',
    acceptedOverride: ['Big deal', 'A big deal'],
    explanation: 'DEAL is written very big.',
    layout: 'big-deal',
    tokens: ['DEAL'],
  },
  {
    id: 'swys-small-talk',
    answer: 'Small talk',
    acceptedOverride: ['Small talk'],
    explanation: 'TALK is written very small.',
    layout: 'small-talk',
    tokens: ['TALK'],
  },
  {
    id: 'swys-left-out',
    answer: 'Left out',
    acceptedOverride: ['Left out', 'Left outside'],
    explanation: 'LEFT is outside the box.',
    layout: 'left-out',
    tokens: ['LEFT'],
  },
  {
    id: 'swys-crossroads',
    answer: 'Crossroads',
    acceptedOverride: ['Crossroads', 'Cross roads'],
    explanation: 'Two roads cross each other.',
    layout: 'crossroads',
    tokens: ['ROAD', 'ROAD'],
  },
  {
    id: 'swys-apple-turnover',
    answer: 'Apple turnover',
    acceptedOverride: ['Apple turnover', 'Turnover apple'],
    explanation: 'APPLE has been turned over.',
    layout: 'apple-turnover',
    tokens: ['APPLE'],
  },
  {
    id: 'swys-safe-and-sound',
    answer: 'Safe and sound',
    acceptedOverride: ['Safe and sound'],
    explanation: 'SAFE is surrounded by sound waves.',
    layout: 'safe-sound',
    tokens: ['SAFE', 'SOUND'],
  },
  {
    id: 'swys-cut-above',
    answer: 'A cut above',
    acceptedOverride: ['A cut above', 'Cut above'],
    explanation: 'CUT is above the line.',
    layout: 'cut-above',
    tokens: ['CUT'],
  },
  {
    id: 'swys-blue-moon',
    answer: 'Once in a blue moon',
    acceptedOverride: ['Once in a blue moon', 'One in a blue moon', 'In a blue moon'],
    explanation: 'ONE is inside a blue moon.',
    layout: 'blue-moon',
    tokens: ['ONE', 'MOON'],
  },
  {
    id: 'swys-long-story-short',
    answer: 'Long story short',
    acceptedOverride: ['Long story short'],
    explanation: 'STORY starts long and ends short.',
    layout: 'long-story-short',
    tokens: ['STORY', 'SHORT'],
  },
  {
    id: 'swys-eye-in-the-sky',
    answer: 'Eye in the sky',
    acceptedOverride: ['Eye in the sky', 'An eye in the sky'],
    explanation: 'EYE is high up in the sky.',
    layout: 'eye-sky',
    tokens: ['EYE', 'SKY'],
  },
  {
    id: 'swys-count-me-in',
    answer: 'Count me in',
    acceptedOverride: ['Count me in'],
    explanation: 'ME is inside COUNT.',
    layout: 'count-me-in',
    tokens: ['COUNT', 'ME'],
  },
  {
    id: 'swys-all-over-the-place',
    answer: 'All over the place',
    acceptedOverride: ['All over the place'],
    explanation: 'ALL appears all over the board.',
    layout: 'all-over-place',
    tokens: ['ALL', 'ALL', 'ALL', 'ALL'],
  },
  {
    id: 'swys-no-idea',
    answer: 'No idea',
    acceptedOverride: ['No idea'],
    explanation: 'IDEA has a big NO across it.',
    layout: 'no-idea',
    tokens: ['IDEA', 'NO'],
  },
  {
    id: 'swys-right-on-time',
    answer: 'Right on time',
    acceptedOverride: ['Right on time'],
    explanation: 'RIGHT is sitting on TIME.',
    layout: 'right-on-time',
    tokens: ['RIGHT', 'TIME'],
  },
  {
    id: 'swys-blank-space',
    answer: 'Blank space',
    acceptedOverride: ['Blank space', 'A blank space'],
    explanation: 'There is a blank space between the words.',
    layout: 'blank-space',
    tokens: ['BLANK', 'SPACE'],
  },
  {
    id: 'swys-stand-by-me',
    answer: 'Stand by me',
    acceptedOverride: ['Stand by me'],
    explanation: 'STAND is right by ME.',
    layout: 'stand-by-me',
    tokens: ['STAND', 'ME'],
  },
  {
    id: 'swys-inside-job',
    answer: 'Inside job',
    acceptedOverride: ['Inside job', 'An inside job'],
    explanation: 'JOB is inside the box.',
    layout: 'inside-job',
    tokens: ['JOB'],
  },
]

export function selectSayWhatYouSeePuzzles(count = 10, usedQuestionIds) {
  return selectPrompts(sayWhatYouSeePuzzles, count, usedQuestionIds)
}
