export const extraMajorityPrompts = [
  { id: 'morning-drink', prompt: 'What is the best first drink of the day?', options: ['Coffee', 'Tea', 'Water', 'Juice'] },
  { id: 'group-chat-reaction', prompt: 'Which group-chat reply gets used the most?', options: ['A thumbs up', 'A laugh reaction', 'No reply', 'A voice note'] },
  { id: 'airport-activity', prompt: 'What is the best way to pass time at an airport?', options: ['Browse shops', 'Eat something', 'Read', 'People-watch'] },
  { id: 'holiday-weather', prompt: 'What weather is most disappointing on holiday?', options: ['Heavy rain', 'Too hot', 'Strong wind', 'Cold evenings'] },
  { id: 'family-game-power', prompt: 'Which game-night power would you choose?', options: ['Reroll once', 'Skip a turn', 'Steal a point', 'See one answer'] },
  { id: 'takeaway-side', prompt: 'Which takeaway side dish disappears first?', options: ['Chips', 'Garlic bread', 'Spring rolls', 'Onion rings'] },
  { id: 'best-seat-cinema', prompt: 'Where is the best seat in the cinema?', options: ['Middle-middle', 'Back row', 'Aisle seat', 'Front row'] },
  { id: 'bad-present', prompt: 'What makes the worst present?', options: ['Wrong size', 'No thought', 'Too practical', 'Clearly regifted'] },
  { id: 'home-comfort', prompt: 'Which small comfort improves a home the most?', options: ['Good lighting', 'Soft blankets', 'Fresh sheets', 'A tidy kitchen'] },
  { id: 'weekend-errand', prompt: 'Which weekend errand is most annoying?', options: ['Food shop', 'Post office', 'Petrol station', 'Returns'] },
  { id: 'voice-note', prompt: 'What is the acceptable length for a voice note?', options: ['Under 10 seconds', 'Under 30 seconds', 'One minute', 'Any length'] },
  { id: 'best-leftover', prompt: 'Which food is best as leftovers?', options: ['Curry', 'Pizza', 'Lasagne', 'Roast dinner'] },
  { id: 'hotel-extra', prompt: 'Which hotel extra feels most luxurious?', options: ['Late checkout', 'Room service', 'A pool', 'Great breakfast'] },
  { id: 'shoe-choice', prompt: 'Which footwear is hardest to live without?', options: ['Trainers', 'Slippers', 'Boots', 'Sandals'] },
  { id: 'shopping-queue', prompt: 'Which checkout queue do people pick?', options: ['Shortest line', 'Fewest baskets', 'Self-checkout', 'Staffed till'] },
  { id: 'best-table-game', prompt: 'What makes a table game fun?', options: ['Fast rounds', 'Comebacks', 'Arguments', 'Simple rules'] },
  { id: 'social-plan', prompt: 'Which social plan is easiest to agree on?', options: ['Dinner', 'Cinema', 'Coffee', 'Walk'] },
  { id: 'forgotten-password', prompt: 'What is most annoying about forgotten passwords?', options: ['Reset email delays', 'Security questions', 'New password rules', 'Two-factor codes'] },
  { id: 'car-snack', prompt: 'Which snack is best for a long car journey?', options: ['Crisps', 'Sweets', 'Fruit', 'Chocolate'] },
  { id: 'tv-genre', prompt: 'Which TV genre is safest for a group?', options: ['Comedy', 'Quiz show', 'Documentary', 'Drama'] },
]
