export const familyNightMajorityPrompts = [
  { id: 'fn-majority-sunday-dinner', prompt: 'Which part of a Sunday dinner matters most?', options: ['Roast potatoes', 'Gravy', 'Meat', 'Stuffing'] },
  { id: 'fn-majority-text-reply', prompt: 'What is the most acceptable short text reply?', options: ['OK', 'Grand', 'Sure', 'Thanks'] },
  { id: 'fn-majority-dream-room', prompt: 'Which room would you upgrade first?', options: ['Kitchen', 'Living room', 'Bedroom', 'Bathroom'] },
  { id: 'fn-majority-best-crisp', prompt: 'Which crisp flavour is safest for a group?', options: ['Cheese and onion', 'Salt and vinegar', 'Ready salted', 'Prawn cocktail'] },
  { id: 'fn-majority-tv-volume', prompt: 'Who should control the TV volume?', options: ['The host', 'Whoever is closest', 'The oldest person', 'Nobody, leave it alone'] },
  { id: 'fn-majority-fast-food', prompt: 'Which fast-food order is the safest bet?', options: ['Burger and chips', 'Chicken meal', 'Pizza slice', 'Wrap'] },
  { id: 'fn-majority-cleaning', prompt: 'Which cleaning job feels most satisfying when done?', options: ['Vacuuming', 'Fresh sheets', 'Cleaning the kitchen', 'Clearing clutter'] },
  { id: 'fn-majority-family-photo', prompt: 'What ruins a family photo most often?', options: ['Someone blinking', 'Bad lighting', 'Someone looking away', 'Too many retakes'] },
  { id: 'fn-majority-game-night-seat', prompt: 'Where is the best seat for game night?', options: ['Near the snacks', 'Near the screen', 'At the end', 'Beside your teammate'] },
  { id: 'fn-majority-lost-remote', prompt: 'Where is the TV remote most likely hiding?', options: ['Down the sofa', 'Under a cushion', 'On the floor', 'In the kitchen'] },
  { id: 'fn-majority-cup-of-tea', prompt: 'What matters most in a cup of tea?', options: ['Strength', 'Milk amount', 'Temperature', 'The biscuit beside it'] },
  { id: 'fn-majority-best-biscuit', prompt: 'Which biscuit disappears first?', options: ['Chocolate digestive', 'Custard cream', 'Bourbon', 'Rich tea'] },
  { id: 'fn-majority-pub-snack', prompt: 'Which pub snack wins?', options: ['Crisps', 'Nuts', 'Chips', 'Chicken wings'] },
  { id: 'fn-majority-car-control', prompt: 'What is the most contested car setting?', options: ['Radio station', 'Temperature', 'Window open', 'Sat nav route'] },
  { id: 'fn-majority-house-smell', prompt: 'Which smell makes a house feel welcoming?', options: ['Fresh bread', 'Clean laundry', 'Dinner cooking', 'Coffee'] },
  { id: 'fn-majority-party-game', prompt: 'Which game-night moment gets the biggest reaction?', options: ['A comeback', 'A wrong confident answer', 'A tie-break', 'Someone bluffing'] },
  { id: 'fn-majority-phone-battery', prompt: 'At what battery percentage do people start to panic?', options: ['20%', '10%', '5%', '1%'] },
  { id: 'fn-majority-best-toast', prompt: 'What belongs on hot toast first?', options: ['Butter', 'Jam', 'Cheese', 'Nothing yet'] },
  { id: 'fn-majority-quiet-hour', prompt: 'What is the best quiet-hour activity?', options: ['Reading', 'Nap', 'TV', 'A walk'] },
  { id: 'fn-majority-sweets', prompt: 'Which sweet bag is safest to share?', options: ['Jellies', 'Chocolate buttons', 'Mints', 'Fizzy sweets'] },
  { id: 'fn-majority-shopping-list', prompt: 'What is most often forgotten from the shopping list?', options: ['Milk', 'Bread', 'Toilet roll', 'Something for dinner'] },
  { id: 'fn-majority-kitchen-gadget', prompt: 'Which kitchen gadget earns its space?', options: ['Air fryer', 'Toaster', 'Blender', 'Slow cooker'] },
  { id: 'fn-majority-best-queue', prompt: 'Which queue looks fastest?', options: ['Self-checkout', 'One full trolley', 'Two small baskets', 'The moving one'] },
  { id: 'fn-majority-weather-plan', prompt: 'What is the first plan cancelled by bad weather?', options: ['Walk', 'Barbecue', 'Shopping trip', 'Outdoor sport'] },
  { id: 'fn-majority-celebration-food', prompt: 'What food says celebration most clearly?', options: ['Cake', 'Takeaway', 'Roast dinner', 'Finger food'] },
]
