export const additionalQuestions = [
  {
    id: 'all-months',
    difficulty: 90,
    type: 'choice',
    prompt: 'How many months have 28 days?',
    options: ['1', '2', '11', '12'],
    answer: '12',
    explanation: 'Every month has at least 28 days.',
  },
  {
    id: 'day-after-tomorrow',
    difficulty: 90,
    type: 'choice',
    prompt: 'If yesterday was Thursday, what day is the day after tomorrow?',
    options: ['Saturday', 'Sunday', 'Monday'],
    answer: 'Sunday',
    explanation: 'Today is Friday, so the day after tomorrow is Sunday.',
  },
  {
    id: 'silent-first-letter',
    difficulty: 90,
    type: 'choice',
    prompt: 'Which word sounds the same when its first letter is removed?',
    options: ['KNIGHT', 'PLANE', 'STONE'],
    answer: 'KNIGHT',
    explanation: 'KNIGHT becomes NIGHT, which is pronounced in the same way.',
  },
  {
    id: 'odd-number-sequence',
    difficulty: 80,
    type: 'input',
    prompt: 'What number comes next?',
    detail: '2  ·  3  ·  5  ·  8  ·  12  ·  ?',
    answer: ['17', 'seventeen'],
    explanation: 'The gaps increase by one each time: +1, +2, +3, +4, then +5.',
  },
  {
    id: 'family-siblings',
    difficulty: 80,
    type: 'input',
    prompt: 'Two parents have three children. Each child has two siblings. How many people are in the family?',
    answer: ['5', 'five'],
    explanation: 'The three children share the same two siblings, making five people altogether.',
  },
  {
    id: 'same-backwards',
    difficulty: 80,
    type: 'choice',
    prompt: 'Which word reads the same from left to right and right to left?',
    options: ['LEVEL', 'LEVER', 'REVEL'],
    answer: 'LEVEL',
    explanation: 'LEVEL is a palindrome.',
  },
  {
    id: 'month-initials',
    difficulty: 70,
    type: 'input',
    prompt: 'Which letter replaces the question mark?',
    detail: 'J  F  M  A  M  J  J  ?  S  O  N  D',
    answer: ['a'],
    explanation: 'These are the first letters of the months, so the missing month is August.',
  },
  {
    id: 'alphabet-value-cat',
    difficulty: 70,
    type: 'input',
    prompt: 'If A = 1, B = 2 and so on, what is the value of CAT?',
    answer: ['24', 'twenty four', 'twenty-four'],
    explanation: 'C is 3, A is 1 and T is 20. Together they total 24.',
  },
  {
    id: 'maya-sisters',
    difficulty: 70,
    type: 'choice',
    prompt: 'Maya has three brothers. Each brother has two sisters. How many sisters does Maya have?',
    options: ['1', '2', '3', '6'],
    answer: '2',
    explanation: 'The brothers share the same two sisters, one of whom is Maya.',
  },
  {
    id: 'anagram-listen',
    difficulty: 60,
    type: 'choice',
    prompt: 'Which option uses exactly the same letters as LISTEN?',
    options: ['SILENT', 'ENLISTS', 'TINSELLED'],
    answer: 'SILENT',
    explanation: 'SILENT is an exact anagram of LISTEN.',
  },
  {
    id: 'hundred-hours',
    difficulty: 60,
    type: 'input',
    prompt: 'It is noon on Monday. What day will it be 100 hours later?',
    answer: ['friday'],
    explanation: 'Ninety-six hours is four full days, taking us to Friday, plus another four hours.',
  },
  {
    id: 'letter-count-number',
    difficulty: 60,
    type: 'choice',
    prompt: 'Which number has the same number of letters in its name as its value?',
    options: ['THREE', 'FOUR', 'FIVE', 'SIX'],
    answer: 'FOUR',
    explanation: 'FOUR has four letters.',
  },
  {
    id: 'count-digit-one',
    difficulty: 50,
    type: 'input',
    prompt: 'How many times is the digit 1 written when listing every whole number from 1 to 20?',
    answer: ['12', 'twelve'],
    explanation: 'Count 1, 10, both digits in 11, and one in each number from 12 to 19.',
  },
  {
    id: 'machines-widgets',
    difficulty: 50,
    type: 'input',
    prompt: 'Five machines make five widgets in five minutes. How long would 100 machines take to make 100 widgets?',
    answer: ['5', 'five', '5 minutes', 'five minutes'],
    explanation: 'Each machine makes one widget in five minutes.',
  },
  {
    id: 'middle-alphabet',
    difficulty: 50,
    type: 'choice',
    prompt: 'Which two letters sit exactly in the middle of the English alphabet?',
    options: ['L and M', 'M and N', 'N and O'],
    answer: 'M and N',
    explanation: 'There are 12 letters before M and 12 letters after N.',
  },
  {
    id: 'minute-moment',
    difficulty: 40,
    type: 'input',
    prompt: 'What appears once in a minute, twice in a moment, but never in a thousand years?',
    answer: ['m', 'the letter m', 'letter m'],
    explanation: 'It is the letter M.',
  },
  {
    id: 'country-from-plan',
    difficulty: 40,
    type: 'input',
    prompt: 'Add one letter to PLAN and rearrange all five letters to make a country.',
    answer: ['nepal'],
    explanation: 'Adding E and rearranging the letters gives NEPAL.',
  },
  {
    id: 'three-daughters',
    difficulty: 40,
    type: 'input',
    prompt: 'A mother has three daughters. Each daughter has one brother. How many children does the mother have?',
    answer: ['4', 'four'],
    explanation: 'All three daughters share the same brother.',
  },
  {
    id: 'two-fathers',
    difficulty: 30,
    type: 'input',
    prompt: 'Two fathers and two sons go fishing. Each catches one fish, but they bring home only three fish. How?',
    answer: ['3', 'three', 'grandfather father son', 'a grandfather a father and a son'],
    explanation: 'There are only three people: a grandfather, his son, and his grandson.',
  },
  {
    id: 'bat-and-ball',
    difficulty: 30,
    type: 'input',
    prompt: 'A bat and ball cost €1.10 altogether. The bat costs €1 more than the ball. How much does the ball cost?',
    answer: ['5c', '5 cents', 'five cents', '€0.05', '0.05'],
    explanation: 'The ball costs 5 cents and the bat costs €1.05.',
  },
  {
    id: 'palindrome-after-999',
    difficulty: 30,
    type: 'input',
    prompt: 'What is the next whole number after 999 that reads the same forwards and backwards?',
    answer: ['1001', '1,001'],
    explanation: '1001 is the first palindrome after 999.',
  },
  {
    id: 'overtake-second',
    difficulty: 20,
    type: 'choice',
    prompt: 'In a race, you overtake the person in second place. What position are you now in?',
    options: ['First', 'Second', 'Third'],
    answer: 'Second',
    explanation: 'You take the position of the person you overtook.',
  },
  {
    id: 'eight-eights',
    difficulty: 20,
    type: 'input',
    prompt: 'Use all eight of these 8s to make 1,000 using only addition.',
    detail: '8  8  8  8  8  8  8  8',
    answer: ['888+88+8+8+8', '888 + 88 + 8 + 8 + 8'],
    explanation: '888 + 88 + 8 + 8 + 8 = 1,000.',
  },
  {
    id: 'snail-climb',
    difficulty: 20,
    type: 'input',
    prompt: 'A snail climbs 3 metres each day and slips 2 metres each night. On which day does it first reach the top of a 10-metre wall?',
    answer: ['8', 'eight', 'day 8', 'day eight'],
    explanation: 'It begins day eight at 7 metres and reaches 10 before it can slip back.',
  },
  {
    id: 'lily-pond',
    difficulty: 10,
    type: 'input',
    prompt: 'A patch of lilies doubles in size every day and covers a pond on day 48. On which day was the pond half covered?',
    answer: ['47', 'forty seven', 'forty-seven', 'day 47'],
    explanation: 'Because it doubles each day, it was half covered one day earlier.',
  },
  {
    id: 'locker-switches',
    difficulty: 10,
    type: 'input',
    prompt: 'There are 100 closed lockers. Locker 1 is toggled every turn, locker 2 every second turn, and so on for 100 turns. How many finish open?',
    answer: ['10', 'ten'],
    explanation: 'Only perfect-square lockers are toggled an odd number of times: 1, 4, 9, up to 100.',
  },
  {
    id: 'two-ropes',
    difficulty: 10,
    type: 'choice',
    prompt: 'Two uneven ropes each take one hour to burn. Which method measures exactly 45 minutes?',
    options: [
      'Burn one rope, then half of the other',
      'Light one at both ends and one at one end; when the first finishes, light the other end',
      'Light both ropes at one end and wait',
    ],
    answer: 'Light one at both ends and one at one end; when the first finishes, light the other end',
    explanation: 'The first rope takes 30 minutes. The remaining rope then burns from both ends for 15 minutes.',
  },
  {
    id: 'wrong-label-boxes',
    difficulty: 1,
    type: 'choice',
    prompt: 'Three boxes are labelled APPLES, ORANGES and MIXED, but every label is wrong. You may take one fruit from one box. Which box must you choose?',
    options: ['APPLES', 'ORANGES', 'MIXED'],
    answer: 'MIXED',
    explanation: 'That box cannot be mixed, so one draw identifies its contents and lets you deduce the others.',
  },
  {
    id: 'clock-addition',
    difficulty: 1,
    type: 'input',
    prompt: 'Without changing the numbers, when can 9 + 5 equal 2?',
    answer: ['on a clock', 'clock', 'time', '2 oclock', "2 o'clock"],
    explanation: 'On a 12-hour clock, five hours after 9 o’clock is 2 o’clock.',
  },
  {
    id: 'look-and-say',
    difficulty: 1,
    type: 'input',
    prompt: 'What number comes next in this sequence?',
    detail: '1  ·  11  ·  21  ·  1211  ·  111221  ·  ?',
    answer: ['312211'],
    explanation: 'Read the previous term aloud: three 1s, two 2s, one 1 gives 312211.',
  },
]
