export const extraQuestions = [
  {
    id: 'one-percent-spare-chair',
    difficulty: 90,
    type: 'choice',
    prompt: 'Four people sit around a table. One leaves. How many chairs are still at the table?',
    options: ['3', '4', '5'],
    answer: '4',
    explanation: 'The person leaves, but the chair does not.',
  },
  {
    id: 'one-percent-before-tuesday',
    difficulty: 90,
    type: 'input',
    prompt: 'What day comes immediately before Tuesday?',
    answer: ['monday'],
    explanation: 'Monday is the day before Tuesday.',
  },
  {
    id: 'one-percent-rainbow-letter',
    difficulty: 80,
    type: 'input',
    prompt: 'How many letters are in the word RAINBOW?',
    answer: ['7', 'seven'],
    explanation: 'R-A-I-N-B-O-W has seven letters.',
  },
  {
    id: 'one-percent-even-months',
    difficulty: 80,
    type: 'choice',
    prompt: 'Which month has an even number of letters?',
    options: ['March', 'April', 'May'],
    answer: 'April',
    explanation: 'April has six letters. March and May have odd letter counts.',
  },
  {
    id: 'one-percent-bookends',
    difficulty: 70,
    type: 'input',
    prompt: 'What word is made by the first and last letters of TABLE?',
    answer: ['te'],
    explanation: 'The first letter is T and the last is E.',
  },
  {
    id: 'one-percent-before-after',
    difficulty: 70,
    type: 'choice',
    prompt: 'Which word can go after BLUE and before BIRD?',
    options: ['Sky', 'Bell', 'Black'],
    answer: 'Bell',
    explanation: 'Bluebell and bellbird are both words.',
  },
  {
    id: 'one-percent-calendar-middle',
    difficulty: 60,
    type: 'input',
    prompt: 'In a non-leap year, which month is exactly halfway through the calendar by month number?',
    answer: ['june', '6'],
    explanation: 'June is the sixth month, halfway through the twelve named months.',
  },
  {
    id: 'one-percent-alphabet-neighbours',
    difficulty: 60,
    type: 'input',
    prompt: 'Which letter is between K and M in the alphabet?',
    answer: ['l'],
    explanation: 'The sequence is K, L, M.',
  },
  {
    id: 'one-percent-repeated-letter',
    difficulty: 50,
    type: 'choice',
    prompt: 'Which word contains exactly one repeated letter?',
    options: ['BALLOON', 'PAPER', 'CLOCK'],
    answer: 'PAPER',
    explanation: 'PAPER has two Ps and every other letter once. BALLOON has two repeated letters.',
  },
  {
    id: 'one-percent-coin-row',
    difficulty: 50,
    type: 'input',
    prompt: 'You have coins worth 1, 2, 5 and 10 cents. How many are worth less than 5 cents?',
    answer: ['2', 'two'],
    explanation: 'The 1-cent and 2-cent coins are less than 5 cents.',
  },
  {
    id: 'one-percent-word-ladder-step',
    difficulty: 40,
    type: 'input',
    prompt: 'Change one letter in COLD to make something valuable and shiny.',
    answer: ['gold'],
    explanation: 'Changing C to G makes GOLD.',
  },
  {
    id: 'one-percent-number-hidden',
    difficulty: 40,
    type: 'input',
    prompt: 'Which number is hidden in the word STONE?',
    answer: ['one', '1'],
    explanation: 'STONE contains the consecutive letters ONE.',
  },
  {
    id: 'one-percent-clock-reflection',
    difficulty: 30,
    type: 'choice',
    prompt: 'On a digital clock, which time reads the same upside down on a seven-segment display?',
    options: ['11:11', '12:21', '15:51'],
    answer: '11:11',
    explanation: 'The digit 1 remains 1 when turned upside down on a seven-segment display.',
  },
  {
    id: 'one-percent-vowel-order',
    difficulty: 30,
    type: 'input',
    prompt: 'What is the only vowel missing from this list?',
    detail: 'A  E  I  O',
    answer: ['u'],
    explanation: 'The standard vowels are A, E, I, O and U.',
  },
  {
    id: 'one-percent-double-days',
    difficulty: 20,
    type: 'input',
    prompt: 'Which two consecutive days start with the same letter?',
    answer: ['saturday sunday', 'saturday and sunday', 'sunday saturday'],
    explanation: 'Saturday and Sunday both begin with S and are consecutive.',
  },
  {
    id: 'one-percent-number-words',
    difficulty: 20,
    type: 'input',
    prompt: 'What is the first whole number whose English name contains the letter A?',
    answer: ['one thousand', '1000', 'a thousand'],
    explanation: 'From one to nine hundred ninety-nine, no standard English number name uses A.',
  },
  {
    id: 'one-percent-shared-ending',
    difficulty: 10,
    type: 'input',
    prompt: 'What three-letter ending can follow SUN, MOON and STAR to make common words?',
    answer: ['lit'],
    explanation: 'Sunlit, moonlit and starlit are all words.',
  },
  {
    id: 'one-percent-alphabet-product',
    difficulty: 10,
    type: 'input',
    prompt: 'If A=1 and Z=26, what is the difference between Z and A?',
    answer: ['25', 'twenty five', 'twenty-five'],
    explanation: '26 minus 1 is 25.',
  },
  {
    id: 'one-percent-hidden-colours',
    difficulty: 1,
    type: 'input',
    prompt: 'What colour appears if you take the capital letters from “briGht Rooms Enjoy Easy Nights”?',
    answer: ['green'],
    explanation: 'The capital letters spell GREEN.',
  },
  {
    id: 'one-percent-every-other',
    difficulty: 1,
    type: 'input',
    prompt: 'Take every other letter from HXEYALRXT, starting with the first letter. What word appears?',
    answer: ['heart'],
    explanation: 'The first, third, fifth, seventh and ninth letters spell HEART.',
  },
]
