export const familyNightQuestions = [
  {
    id: 'fn-op-90-calendar-order',
    difficulty: 90,
    type: 'choice',
    prompt: 'Which month comes earliest in a dictionary?',
    options: ['April', 'August', 'December'],
    answer: 'April',
    explanation: 'April comes before August and December alphabetically.',
  },
  {
    id: 'fn-op-90-letter-holes',
    difficulty: 90,
    type: 'input',
    prompt: 'In uppercase, how many enclosed spaces are in the word BALLOON?',
    answer: ['4', 'four'],
    explanation: 'B has two enclosed spaces, A has one, and O has one. The other letters have none.',
  },
  {
    id: 'fn-op-80-weekend-days',
    difficulty: 80,
    type: 'input',
    prompt: 'If yesterday was Friday, what day is tomorrow?',
    answer: ['sunday'],
    explanation: 'Today is Saturday, so tomorrow is Sunday.',
  },
  {
    id: 'fn-op-80-silent-letter',
    difficulty: 80,
    type: 'choice',
    prompt: 'Which word contains a silent first letter?',
    options: ['Knight', 'Bright', 'Flight'],
    answer: 'Knight',
    explanation: 'The K in knight is silent.',
  },
  {
    id: 'fn-op-70-repeated-letter',
    difficulty: 70,
    type: 'input',
    prompt: 'Which letter appears twice in both PEPPER and PUPPY?',
    answer: ['p'],
    explanation: 'P appears twice in PEPPER and twice in PUPPY.',
  },
  {
    id: 'fn-op-70-last-alphabet',
    difficulty: 70,
    type: 'choice',
    prompt: 'Which word would appear last in a dictionary?',
    options: ['Plate', 'Plant', 'Plane'],
    answer: 'Plate',
    explanation: 'All begin with PLA, and T comes after N.',
  },
  {
    id: 'fn-op-60-clock-angle',
    difficulty: 60,
    type: 'input',
    prompt: 'At exactly 6 o clock, how many degrees are between the clock hands?',
    answer: ['180', 'one hundred and eighty'],
    explanation: 'The minute hand points to 12 and the hour hand points to 6, making a straight line.',
  },
  {
    id: 'fn-op-60-word-chain',
    difficulty: 60,
    type: 'input',
    prompt: 'What word links these three?',
    detail: 'BIRTH ___  ·  ___ LIGHT  ·  PLAY ___',
    answer: ['day'],
    explanation: 'Birthday, daylight and playday all work.',
  },
  {
    id: 'fn-op-50-number-words',
    difficulty: 50,
    type: 'input',
    prompt: 'How many letters are in the number word SEVENTEEN?',
    answer: ['9', 'nine'],
    explanation: 'SEVENTEEN has nine letters.',
  },
  {
    id: 'fn-op-50-opposite-sides',
    difficulty: 50,
    type: 'choice',
    prompt: 'Which pair of opposites has the same number of letters in both words?',
    options: ['Hot and cold', 'Give and take', 'Left and right'],
    answer: 'Give and take',
    explanation: 'GIVE and TAKE are opposites in a phrase, and both have four letters.',
  },
  {
    id: 'fn-op-40-fifth-vowel',
    difficulty: 40,
    type: 'input',
    prompt: 'What is the fifth vowel in this sentence?',
    detail: 'A clever idea is often simple.',
    answer: ['e'],
    explanation: 'Counting vowels: A, e, e, i, e. The fifth is E.',
  },
  {
    id: 'fn-op-40-family-ages',
    difficulty: 40,
    type: 'input',
    prompt: 'Anna is 12. Ben is half Anna’s age. In six years, how old will Ben be?',
    answer: ['12', 'twelve'],
    explanation: 'Ben is 6 now, so in six years he will be 12.',
  },
  {
    id: 'fn-op-30-alphabet-skip',
    difficulty: 30,
    type: 'input',
    prompt: 'What letter comes next?',
    detail: 'A  C  F  J  O  ?',
    answer: ['u'],
    explanation: 'The gaps increase by one letter each time: +2, +3, +4, +5, then +6.',
  },
  {
    id: 'fn-op-30-common-ending',
    difficulty: 30,
    type: 'input',
    prompt: 'What word can go after all three to make familiar phrases?',
    detail: 'FAMILY  ·  BOARD  ·  VIDEO',
    answer: ['game', 'games'],
    explanation: 'Family game, board game and video game.',
  },
  {
    id: 'fn-op-20-alphabet-maths',
    difficulty: 20,
    type: 'input',
    prompt: 'If A = 1 and Z = 26, what is C + O + D + E?',
    answer: ['27', 'twenty seven'],
    explanation: 'C is 3, O is 15, D is 4 and E is 5. Total: 27.',
  },
  {
    id: 'fn-op-20-hidden-number',
    difficulty: 20,
    type: 'input',
    prompt: 'Which number is hidden across these words?',
    detail: 'BRIGH T W O RDS',
    answer: ['two', '2'],
    explanation: 'TWO is hidden across the spaces.',
  },
  {
    id: 'fn-op-10-missing-pair',
    difficulty: 10,
    type: 'input',
    prompt: 'What two letters complete the pattern?',
    detail: 'AZ  BY  CX  DW  ?',
    answer: ['ev', 'e v'],
    explanation: 'The first letter moves forward while the second moves backward.',
  },
  {
    id: 'fn-op-10-reading-order',
    difficulty: 10,
    type: 'input',
    prompt: 'Read every second word starting with the second. What phrase appears?',
    detail: 'Never TRUST quiet THE clocks PROCESS after midnight',
    answer: ['trust the process'],
    explanation: 'The 2nd, 4th and 6th words spell TRUST THE PROCESS.',
  },
  {
    id: 'fn-op-1-word-ladder',
    difficulty: 1,
    type: 'input',
    prompt: 'Change one letter at a time to go from COLD to WARM in four valid English words. What is one possible second word?',
    detail: 'COLD -> ____ -> WARD -> WARM',
    answer: ['cord'],
    explanation: 'COLD can become CORD, then WARD, then WARM by changing one letter each step.',
  },
  {
    id: 'fn-op-1-letter-trap',
    difficulty: 1,
    type: 'input',
    prompt: 'What word is hidden when you take the first letter after each number?',
    detail: '1T apple 2R book 3I chair 4C door 5K egg',
    answer: ['trick'],
    explanation: 'The letters after the numbers spell T, R, I, C, K.',
  },
]
