export const moreQuestions = [
  {
    id: 'one-kilo-weight',
    difficulty: 90,
    type: 'choice',
    prompt: 'Which is heavier?',
    options: ['1 kg of feathers', '1 kg of bricks', 'They weigh the same'],
    answer: 'They weigh the same',
    explanation: 'Both weigh exactly one kilogram.',
  },
  {
    id: 'friday-three-times',
    difficulty: 90,
    type: 'input',
    prompt: 'A woman says, “I saw Friday three times this week.” How is that possible?',
    answer: ['friday is a person', 'friday was a person', 'a person named friday', 'someone named friday'],
    explanation: 'Friday is the name of a person she saw three times.',
  },
  {
    id: 'empty-basket',
    difficulty: 90,
    type: 'choice',
    prompt: 'How many eggs can you put into an empty basket?',
    options: ['One', 'Six', 'As many as will fit'],
    answer: 'One',
    explanation: 'After the first egg goes in, the basket is no longer empty.',
  },
  {
    id: 'clock-strikes',
    difficulty: 80,
    type: 'input',
    prompt: 'A clock takes 5 seconds to strike 6 o’clock. How long does it take to strike 12 o’clock?',
    answer: ['11', '11 seconds', 'eleven', 'eleven seconds'],
    explanation: 'Six strikes have five gaps. Twelve strikes have eleven gaps, so they take 11 seconds.',
  },
  {
    id: 'word-pronounced-wrong',
    difficulty: 80,
    type: 'choice',
    prompt: 'Which word in the dictionary is always pronounced wrong?',
    options: ['Wrong', 'Dictionary', 'Pronounced'],
    answer: 'Wrong',
    explanation: 'The word “wrong” is always pronounced “wrong.”',
  },
  {
    id: 'four-daughters-brother',
    difficulty: 80,
    type: 'input',
    prompt: 'A father has four daughters, and every daughter has one brother. How many children does he have?',
    answer: ['5', 'five'],
    explanation: 'The four daughters share the same brother.',
  },
  {
    id: 'missing-letter-days',
    difficulty: 70,
    type: 'input',
    prompt: 'Which letter begins the only day of the week that does not end in Y?',
    answer: ['n', 'none', 'no letter'],
    explanation: 'Every day of the week ends in Y, so there is no such letter.',
  },
  {
    id: 'book-pages',
    difficulty: 70,
    type: 'input',
    prompt: 'Two facing pages in a book add up to 101. What are the page numbers?',
    answer: ['50 and 51', '50, 51', '50 51'],
    explanation: 'Facing pages are consecutive, and 50 + 51 = 101.',
  },
  {
    id: 'opposite-direction',
    difficulty: 70,
    type: 'choice',
    prompt: 'Two people face each other. One turns left and the other turns right. Which direction are they now facing?',
    options: ['The same direction', 'Opposite directions', 'It cannot be known'],
    answer: 'The same direction',
    explanation: 'Because they began facing opposite ways, those turns point them in the same direction.',
  },
  {
    id: 'alphabet-halfway',
    difficulty: 60,
    type: 'input',
    prompt: 'What letter is halfway between H and P in the alphabet?',
    answer: ['l'],
    explanation: 'H is 8 and P is 16; halfway is 12, which is L.',
  },
  {
    id: 'three-pills',
    difficulty: 60,
    type: 'input',
    prompt: 'You must take three pills, one every 30 minutes. How long until all three have been taken?',
    answer: ['1 hour', 'one hour', '60 minutes', '60'],
    explanation: 'Take the first immediately, the second after 30 minutes, and the third after 60 minutes.',
  },
  {
    id: 'double-half',
    difficulty: 60,
    type: 'choice',
    prompt: 'Which number is double one half of itself?',
    options: ['Every number', 'Only zero', 'No number'],
    answer: 'Every number',
    explanation: 'Half of any number, doubled, returns the original number.',
  },
  {
    id: 'handshake-three',
    difficulty: 50,
    type: 'input',
    prompt: 'Three people each shake hands with every other person once. How many handshakes happen?',
    answer: ['3', 'three'],
    explanation: 'The pairs are AB, AC and BC: three handshakes.',
  },
  {
    id: 'sequence-squares',
    difficulty: 50,
    type: 'input',
    prompt: 'What number comes next?',
    detail: '1  ·  4  ·  9  ·  16  ·  25  ·  ?',
    answer: ['36', 'thirty six', 'thirty-six'],
    explanation: 'These are consecutive square numbers: 1² through 6².',
  },
  {
    id: 'days-in-two-weeks',
    difficulty: 50,
    type: 'choice',
    prompt: 'How many days are there in two weeks and three days?',
    options: ['14', '16', '17', '21'],
    answer: '17',
    explanation: 'Two weeks is 14 days; adding three gives 17.',
  },
  {
    id: 'remove-first-last',
    difficulty: 40,
    type: 'input',
    prompt: 'What five-letter word becomes shorter when you add two letters to it?',
    answer: ['short'],
    explanation: 'Adding E and R to SHORT makes SHORTER.',
  },
  {
    id: 'sum-one-to-nine',
    difficulty: 40,
    type: 'input',
    prompt: 'What is the sum of every whole number from 1 to 9?',
    answer: ['45', 'forty five', 'forty-five'],
    explanation: 'Pairing the ends gives 10 four times, with 5 left over: 45.',
  },
  {
    id: 'letter-after-sequence',
    difficulty: 40,
    type: 'input',
    prompt: 'Which letter comes next?',
    detail: 'O  ·  T  ·  T  ·  F  ·  F  ·  S  ·  S  ·  ?',
    answer: ['e'],
    explanation: 'They are the first letters of One, Two, Three, Four, Five, Six, Seven, Eight.',
  },
  {
    id: 'three-switches',
    difficulty: 30,
    type: 'input',
    prompt: 'A number is multiplied by 3, then 3 is added, giving 18. What was the number?',
    answer: ['5', 'five'],
    explanation: 'Subtract 3 from 18, then divide 15 by 3.',
  },
  {
    id: 'reverse-addition',
    difficulty: 30,
    type: 'input',
    prompt: 'A two-digit number is four times the sum of its digits. Reversing its digits makes it 18 larger. What is it?',
    answer: ['24', 'twenty four', 'twenty-four'],
    explanation: '2 + 4 = 6, and 4 × 6 = 24. Reversed, 42 is 18 larger.',
  },
  {
    id: 'calendar-cube',
    difficulty: 30,
    type: 'choice',
    prompt: 'Which month can have no full moon?',
    options: ['February', 'June', 'December'],
    answer: 'February',
    explanation: 'A lunar cycle is about 29.5 days, so February can fit entirely between two full moons.',
  },
  {
    id: 'painted-cube',
    difficulty: 20,
    type: 'input',
    prompt: 'A cube is painted on every side, then cut into 27 equal smaller cubes. How many small cubes have paint on exactly two faces?',
    answer: ['12', 'twelve'],
    explanation: 'Each of the 12 edges has one middle cube painted on exactly two faces.',
  },
  {
    id: 'five-digit-pattern',
    difficulty: 20,
    type: 'input',
    prompt: 'What number comes next?',
    detail: '1  ·  2  ·  6  ·  24  ·  120  ·  ?',
    answer: ['720', 'seven hundred and twenty', 'seven hundred twenty'],
    explanation: 'Multiply successively by 2, 3, 4, 5 and then 6.',
  },
  {
    id: 'clock-angle',
    difficulty: 20,
    type: 'input',
    prompt: 'How many degrees apart are the hands of a clock at exactly 3 o’clock?',
    answer: ['90', '90 degrees', 'ninety', 'ninety degrees'],
    explanation: 'The minute hand points to 12 and the hour hand to 3, forming a right angle.',
  },
  {
    id: 'bridge-torch',
    difficulty: 10,
    type: 'input',
    prompt: 'Four people take 1, 2, 7 and 10 minutes to cross a bridge. Two cross at once with one torch. What is the fastest total time?',
    answer: ['17', '17 minutes', 'seventeen', 'seventeen minutes'],
    explanation: '1 and 2 cross, 1 returns, 7 and 10 cross, 2 returns, then 1 and 2 cross: 17 minutes.',
  },
  {
    id: 'three-box-code',
    difficulty: 10,
    type: 'input',
    prompt: 'A three-digit code has digits that add to 9. The first is twice the second, and the third is three times the second. What is the code?',
    answer: ['no solution', 'impossible', 'there is no code', 'no whole number solution'],
    explanation: 'The middle digit is 1.5 only if treated loosely, so no whole-number code exists.',
  },
  {
    id: 'poison-bottle',
    difficulty: 10,
    type: 'input',
    prompt: 'You have 8 bottles and one is heavier. What is the fewest balance-scale weighings needed to guarantee finding it?',
    answer: ['2', 'two'],
    explanation: 'Weigh three against three. The result narrows it to at most three bottles, resolved with one more weighing.',
  },
  {
    id: 'nine-dots-lines',
    difficulty: 1,
    type: 'input',
    prompt: 'What familiar phrase describes solving the classic nine-dot puzzle with four straight lines?',
    answer: ['think outside the box', 'thinking outside the box', 'outside the box'],
    explanation: 'The lines must extend beyond the imaginary square: think outside the box.',
  },
  {
    id: 'birthday-probability',
    difficulty: 1,
    type: 'choice',
    prompt: 'In a room of 23 people, is the chance that two share a birthday above or below 50%?',
    options: ['Above 50%', 'Below 50%', 'Exactly 50%'],
    answer: 'Above 50%',
    explanation: 'With 23 people there are 253 pairs, pushing the probability just above 50%.',
  },
  {
    id: 'missing-dollar',
    difficulty: 1,
    type: 'input',
    prompt: 'Three guests pay €30. They receive €5 back, keep €3 and tip €2. Why is adding the €27 paid and €2 tip misleading?',
    answer: ['the tip is included', 'tip is included in 27', 'the 2 is already in the 27', 'wrong addition'],
    explanation: 'The €27 already consists of the €25 bill plus the €2 tip. It should be compared with the €3 returned.',
  },
]
